"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { loadBrandPresence, loadCapture, loadDashboard, loadHistory, loadVisibility } from "./api";
import type { BadgeEvent, BrandPresence, Capture, CaptureDetail, KeywordOption, NewEntrant, RankHistory, Visibility } from "./types";

type Tab = "captures" | "rank" | "visibility" | "brand" | "badges" | "entrants";
type Dashboard = { captures: { items: Capture[]; total: number }; keywords: KeywordOption[]; badges: { items: BadgeEvent[]; total: number }; entrants: { items: NewEntrant[]; total: number } };
const tabs: [Tab, string][] = [["captures", "Captures"], ["rank", "Rank history"], ["visibility", "Visibility"], ["brand", "Brand presence"], ["badges", "Badge events"], ["entrants", "New entrants"]];
export const formatMetric = (value: number | null, suffix = "") => value === null ? "—" : `${value}${suffix}`;
const date = (value: string) => new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));

export default function RankVisibilityClient() {
  const [data, setData] = useState<Dashboard>({ captures: { items: [], total: 0 }, keywords: [], badges: { items: [], total: 0 }, entrants: { items: [], total: 0 } });
  const [tab, setTab] = useState<Tab>("captures"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [keyword, setKeyword] = useState(""); const [geo, setGeo] = useState(""); const [device, setDevice] = useState(""); const [sku, setSku] = useState("");
  const [detail, setDetail] = useState<CaptureDetail | null>(null); const [history, setHistory] = useState<RankHistory | null>(null); const [metrics, setMetrics] = useState<Visibility | null>(null); const [presence, setPresence] = useState<BrandPresence | null>(null); const [analysisLoading, setAnalysisLoading] = useState(false);
  const refresh = useCallback(async () => { setLoading(true); setError(""); try { const loaded = await loadDashboard(); setData(loaded); setKeyword((current) => current || loaded.keywords[0]?.id || ""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load rank visibility data"); } finally { setLoading(false); } }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  const keywordName = (id: string) => data.keywords.find((item) => item.id === id)?.keyword_text ?? id;
  const captures = useMemo(() => data.captures.items.filter((item) => (!keyword || item.keyword_id === keyword) && (!geo || item.geo_code.toLowerCase().includes(geo.toLowerCase())) && (!device || item.device_profile === device)), [data.captures.items, keyword, geo, device]);
  const latest = data.captures.items[0];
  async function openCapture(id: string) { setAnalysisLoading(true); setError(""); try { setDetail(await loadCapture(id)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load capture"); } finally { setAnalysisLoading(false); } }
  function query() { const params = new URLSearchParams({ keyword_id: keyword, marketplace_product_id: sku.trim() }); if (geo) params.set("geo_code", geo); if (device) params.set("device_profile", device); return params.toString(); }
  async function runAnalysis(kind: "rank" | "visibility") { if (!keyword || !sku.trim()) { setError("Select a keyword and enter a marketplace product ID first."); return; } setAnalysisLoading(true); setError(""); try { if (kind === "rank") setHistory(await loadHistory(query())); else setMetrics(await loadVisibility(query())); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load analysis"); } finally { setAnalysisLoading(false); } }
  async function runPresence() { if (!keyword && !latest) { setError("Select a keyword or capture first."); return; } setAnalysisLoading(true); setError(""); try { const params = new URLSearchParams(keyword ? { keyword_id: keyword } : { capture_id: latest.id }); setPresence(await loadBrandPresence(params.toString())); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load brand presence"); } finally { setAnalysisLoading(false); } }
  return <div className="rank-shell">
    <div className="rank-summary"><Summary label="Tracked captures" value={data.captures.total} /><Summary label="Latest capture" value={latest ? date(latest.captured_at) : "—"} /><Summary label="New entrants" value={data.entrants.total} /><Summary label="Badge changes" value={data.badges.total} /></div>
    <div className="universe-panel"><div className="universe-toolbar"><div className="tabs">{tabs.map(([key, label]) => <button key={key} className={`tab ${tab === key ? "active" : ""}`} onClick={() => setTab(key)}>{label}</button>)}</div><button className="button" onClick={() => void refresh()} disabled={loading}>{loading ? "Refreshing…" : "Refresh"}</button></div>
      {error && <div className="error-banner" role="alert">{error}</div>}
      {(tab === "captures" || tab === "rank" || tab === "visibility" || tab === "brand") && <Filters keywords={data.keywords} keyword={keyword} setKeyword={setKeyword} geo={geo} setGeo={setGeo} device={device} setDevice={setDevice} sku={sku} setSku={setSku} showSku={tab === "rank" || tab === "visibility"} />}
      {loading ? <Loading /> : <>
        {tab === "captures" && <Captures rows={captures} keywordName={keywordName} open={openCapture} />}
        {tab === "rank" && <AnalysisAction label="Load rank history" busy={analysisLoading} run={() => void runAnalysis("rank")} />}
        {tab === "rank" && history && <HistoryTable history={history} />}
        {tab === "visibility" && <AnalysisAction label="Calculate visibility" busy={analysisLoading} run={() => void runAnalysis("visibility")} />}
        {tab === "visibility" && metrics && <VisibilityCards value={metrics} />}
        {tab === "brand" && <AnalysisAction label="Calculate brand presence" busy={analysisLoading} run={() => void runPresence()} />}
        {tab === "brand" && presence && <BrandTable value={presence} />}
        {tab === "badges" && <BadgeTable rows={data.badges.items} keywordName={keywordName} />}
        {tab === "entrants" && <EntrantTable rows={data.entrants.items} keywordName={keywordName} />}
      </>}
    </div>
    {detail && <div className="modal-backdrop"><div className="entity-modal rank-detail"><div className="modal-header"><div><div className="eyebrow">SERP capture</div><h2>{keywordName(detail.keyword_id)}</h2><span className="muted">{date(detail.captured_at)} · {detail.geo_code} · {detail.device_profile}</span></div><button className="icon-button" onClick={() => setDetail(null)}>×</button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Absolute</th><th>Within type</th><th>Page</th><th>Marketplace ID</th><th>Brand</th><th>Placement</th><th>Badges</th><th>Price</th><th>Rating</th><th>Reviews</th></tr></thead><tbody>{detail.results.map((row) => <tr key={row.id}><td>#{row.absolute_position}</td><td>#{row.within_type_position}</td><td>{row.page_number}</td><td>{row.marketplace_product_id}</td><td>{row.brand ?? "Unknown"}</td><td>{row.placement_type.replaceAll("_", " ")}</td><td>{row.badges.join(", ") || "—"}</td><td>{row.displayed_price ? `₹${row.displayed_price}` : "—"}</td><td>{row.rating ?? "—"}</td><td>{row.review_count ?? "—"}</td></tr>)}</tbody></table></div></div></div>}
  </div>;
}

function Summary({ label, value }: { label: string; value: string | number }) { return <div className="card"><span>{label}</span><strong>{value}</strong></div>; }
function Loading() { return <div className="loading-state"><span className="spinner" />Loading live S3 data…</div>; }
function Empty({ title, text }: { title: string; text: string }) { return <div className="empty-state"><strong>{title}</strong><span>{text}</span></div>; }
function Filters({ keywords, keyword, setKeyword, geo, setGeo, device, setDevice, sku, setSku, showSku }: { keywords: KeywordOption[]; keyword: string; setKeyword: (v: string) => void; geo: string; setGeo: (v: string) => void; device: string; setDevice: (v: string) => void; sku: string; setSku: (v: string) => void; showSku: boolean }) { return <div className="keyword-filters"><select value={keyword} onChange={(event) => setKeyword(event.target.value)}><option value="">All keywords</option>{keywords.map((item) => <option key={item.id} value={item.id}>{item.keyword_text}</option>)}</select><input placeholder="Geo / pincode" value={geo} onChange={(event) => setGeo(event.target.value)} /><select value={device} onChange={(event) => setDevice(event.target.value)}><option value="">All devices</option><option value="desktop">Desktop</option><option value="mobile">Mobile</option></select>{showSku && <input placeholder="Marketplace product ID / ASIN" value={sku} onChange={(event) => setSku(event.target.value)} />}</div>; }
function AnalysisAction({ label, busy, run }: { label: string; busy: boolean; run: () => void }) { return <div className="rank-action"><button className="button primary" disabled={busy} onClick={run}>{busy ? "Loading…" : label}</button></div>; }
function Captures({ rows, keywordName, open }: { rows: Capture[]; keywordName: (id: string) => string; open: (id: string) => void }) { if (!rows.length) return <Empty title="No SERP captures yet" text="Ingest a normalized capture through the S3 API to begin tracking visibility." />; return <div className="table-wrap"><table className="data-table"><thead><tr><th>Captured</th><th>Keyword</th><th>Marketplace</th><th>Geo</th><th>Device</th><th>Pages</th><th>Results</th><th></th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{date(row.captured_at)}</td><td>{keywordName(row.keyword_id)}</td><td>{row.marketplace}</td><td>{row.geo_code}</td><td>{row.device_profile}</td><td>{row.page_count}</td><td>{row.result_count}</td><td><button className="text-button" onClick={() => void open(row.id)}>View results</button></td></tr>)}</tbody></table></div>; }
function HistoryTable({ history }: { history: RankHistory }) { if (!history.observations.length) return <Empty title="No rank observations" text="No captures match this keyword, identity and context." />; return <div className="table-wrap"><table className="data-table"><thead><tr><th>Captured</th><th>Absolute rank</th><th>Organic rank</th><th>Placement</th><th>Page</th><th>Price</th></tr></thead><tbody>{history.observations.map((row) => <tr key={`${row.capture_id}-${row.absolute_position}`}><td>{date(row.captured_at)}</td><td>#{row.absolute_position}</td><td>{row.organic_rank ? `#${row.organic_rank}` : "—"}</td><td>{row.placement_type.replaceAll("_", " ")}</td><td>{row.page_number}</td><td>{row.displayed_price ? `₹${row.displayed_price}` : "—"}</td></tr>)}</tbody></table></div>; }
function VisibilityCards({ value }: { value: Visibility }) { return <div className="rank-metrics"><Summary label="Latest rank" value={formatMetric(value.latest_rank, "")} /><Summary label="Best rank" value={formatMetric(value.best_rank)} /><Summary label="Latest organic" value={formatMetric(value.latest_organic_rank)} /><Summary label="Volatility (MARM)" value={value.rank_volatility} /><Summary label="Time in top 3" value={formatMetric(value.time_in_top_3_percent, "%")} /><Summary label="Time in top 10" value={formatMetric(value.time_in_top_10_percent, "%")} /><Summary label="Observations" value={value.observation_count} /></div>; }
function BrandTable({ value }: { value: BrandPresence }) { if (!value.brands.length) return <Empty title="No page-1 brand presence" text="No page-1 observations match this selection." />; return <div className="table-wrap"><table className="data-table"><thead><tr><th>Brand</th><th>Page-1 slots</th><th>Share</th><th>Organic</th><th>Sponsored</th></tr></thead><tbody>{value.brands.map((row) => <tr key={row.brand}><td>{row.brand}</td><td>{row.page_1_slot_count}</td><td>{row.page_1_share_percent}%</td><td>{row.organic_slots}</td><td>{row.sponsored_slots}</td></tr>)}</tbody></table></div>; }
function BadgeTable({ rows, keywordName }: { rows: BadgeEvent[]; keywordName: (id: string) => string }) { if (!rows.length) return <Empty title="No badge changes yet" text="Badge acquisitions and losses appear after comparable captures are ingested." />; return <div className="table-wrap"><table className="data-table"><thead><tr><th>Observed</th><th>Keyword</th><th>SKU</th><th>Brand</th><th>Badge</th><th>Change</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{date(row.observed_at)}</td><td>{keywordName(row.keyword_id)}</td><td>{row.marketplace_product_id}</td><td>{row.brand ?? "Unknown"}</td><td>{row.badge_type.replaceAll("_", " ")}</td><td><span className={`status ${row.event_type === "acquired" ? "approved" : "draft"}`}>{row.event_type}</span></td></tr>)}</tbody></table></div>; }
function EntrantTable({ rows, keywordName }: { rows: NewEntrant[]; keywordName: (id: string) => string }) { if (!rows.length) return <Empty title="No new entrants yet" text="First-time page-1 marketplace identities appear here." />; return <div className="table-wrap"><table className="data-table"><thead><tr><th>First seen</th><th>Keyword</th><th>SKU</th><th>Brand</th><th>Rank</th><th>Geo</th><th>Device</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{date(row.first_seen_at)}</td><td>{keywordName(row.keyword_id)}</td><td>{row.marketplace_product_id}</td><td>{row.brand ?? "Unknown"}</td><td>#{row.rank}</td><td>{row.geo_code}</td><td>{row.device_profile}</td></tr>)}</tbody></table></div>; }
