"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {comparison,dashboard,history} from "./api";
import type {Comparison,Event,HistoryRow,Observation,ProductOption} from "./types";
type Tab="current"|"history"|"offers"|"events"|"comparison";
const tabs:[Tab,string][]=[["current","Current Prices"],["history","History"],["offers","Seller Offers"],["events","Price Events"],["comparison","Comparison"]];
export function formatMoney(value:string|number|null|undefined,currency="INR"){if(value===null||value===undefined||value==="")return "Unavailable";return new Intl.NumberFormat("en-IN",{style:"currency",currency,maximumFractionDigits:2}).format(Number(value))}
export function formatFreshness(minutes:number|null){if(minutes===null)return "Unknown";if(minutes<60)return `${minutes} min ago`;return `${Math.floor(minutes/60)} hr ago`}
export function formatMovement(value:string|null,currency="INR"){if(value===null)return "Unavailable";const amount=Number(value);return `${amount>0?"↑":amount<0?"↓":"—"} ${formatMoney(Math.abs(amount),currency)}`}
const when=(value:string)=>new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));
const latestOnly=(rows:Observation[])=>{const seen=new Set<string>();return rows.filter(x=>{const key=`${x.product_id||x.competitor_product_id||x.marketplace_product_id}:${x.geo_code||"all"}`;if(seen.has(key))return false;seen.add(key);return true})};
export default function PriceMonitoringClient(){
 const [tab,setTab]=useState<Tab>("current"),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [rows,setRows]=useState<Observation[]>([]),[events,setEvents]=useState<Event[]>([]),[products,setProducts]=useState<ProductOption[]>([]),[competitors,setCompetitors]=useState<ProductOption[]>([]);
 const [identityType,setIdentityType]=useState("product_id"),[identity,setIdentity]=useState(""),[geo,setGeo]=useState(""),[historyRows,setHistoryRows]=useState<HistoryRow[]|null>(null),[observation,setObservation]=useState("");
 const [owned,setOwned]=useState(""),[competitor,setCompetitor]=useState(""),[compare,setCompare]=useState<Comparison|null>(null);
 const refresh=useCallback(async()=>{setLoading(true);setError("");try{const data=await dashboard();setRows(data.observations.items);setEvents(data.events.items);setProducts(data.products);setCompetitors(data.competitors);setOwned(x=>x||data.products[0]?.id||"");setCompetitor(x=>x||data.competitors[0]?.id||"");setObservation(x=>x||data.observations.items[0]?.id||"")}catch(e){setError(e instanceof Error?e.message:"Unable to load prices")}finally{setLoading(false)}},[]);useEffect(()=>{void refresh()},[refresh]);
 const current=useMemo(()=>latestOnly(rows),[rows]), selected=rows.find(x=>x.id===observation);const stale=current.filter(x=>Date.now()-new Date(x.observed_at).getTime()>240*60000).length,drops=events.filter(x=>x.event_type==="price_decrease").length;
 async function loadHistory(){if(!identity){setError("Select an identity first.");return}setBusy(true);setError("");try{const q=new URLSearchParams({[identityType]:identity});if(geo)q.set("geo_code",geo);setHistoryRows((await history(q.toString())).items)}catch(e){setError(e instanceof Error?e.message:"Unable to load history")}finally{setBusy(false)}}
 async function runComparison(){if(!owned||!competitor){setError("Select owned and competitor products.");return}setBusy(true);setError("");try{setCompare(await comparison(owned,competitor,geo))}catch(e){setError(e instanceof Error?e.message:"Unable to compare prices")}finally{setBusy(false)}}
 const options=identityType==="product_id"?products:competitors;
 return <div className="rank-shell"><div className="rank-summary"><Card label="Tracked identities" value={current.length}/><Card label="Available now" value={current.filter(x=>x.availability_status==="available").length}/><Card label="Stale observations" value={stale}/><Card label="Observed drops" value={drops}/></div><div className="universe-panel"><div className="universe-toolbar"><div className="tabs">{tabs.map(([key,label])=><button className={`tab ${tab===key?"active":""}`} key={key} onClick={()=>setTab(key)}>{label}</button>)}</div><button className="button" onClick={()=>void refresh()} disabled={loading}>{loading?"Refreshing…":"Refresh"}</button></div>{error&&<div role="alert" className="error-banner">{error}</div>}{loading?<div className="loading-state"><span className="spinner"/>Loading observed prices…</div>:<>{tab==="current"&&<Current rows={current}/>} {tab==="events"&&<Events rows={events}/>} {tab==="offers"&&<><Filters><select value={observation} onChange={e=>setObservation(e.target.value)}><option value="">Select observation</option>{rows.map(x=><option value={x.id} key={x.id}>{x.marketplace_product_id} · {when(x.observed_at)}</option>)}</select></Filters><Offers row={selected}/></>} {tab==="history"&&<><Identity type={identityType} setType={v=>{setIdentityType(v);setIdentity("")}} value={identity} setValue={setIdentity} options={options} geo={geo} setGeo={setGeo}/><Action label="Load history" busy={busy} run={()=>void loadHistory()}/>{historyRows&&<History rows={historyRows}/>}</>} {tab==="comparison"&&<><Filters><select value={owned} onChange={e=>setOwned(e.target.value)}><option value="">Owned product</option>{products.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><select value={competitor} onChange={e=>setCompetitor(e.target.value)}><option value="">Competitor product</option>{competitors.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><input value={geo} onChange={e=>setGeo(e.target.value)} placeholder="Pincode / geo (optional)"/></Filters><Action label="Compare latest prices" busy={busy} run={()=>void runComparison()}/>{compare&&<Compare value={compare}/>}</>}</>}</div></div>
}
function Card({label,value}:{label:string;value:string|number}){return <div className="card"><span>{label}</span><strong>{value}</strong></div>}function Empty({title,text}:{title:string;text:string}){return <div className="empty-state"><strong>{title}</strong><span>{text}</span></div>}function Filters({children}:{children:React.ReactNode}){return <div className="keyword-filters">{children}</div>}function Action({label,busy,run}:{label:string;busy:boolean;run:()=>void}){return <div className="rank-action"><button className="button primary" disabled={busy} onClick={run}>{busy?"Loading…":label}</button></div>}
function Identity({type,setType,value,setValue,options,geo,setGeo}:{type:string;setType:(v:string)=>void;value:string;setValue:(v:string)=>void;options:ProductOption[];geo:string;setGeo:(v:string)=>void}){return <Filters><select value={type} onChange={e=>setType(e.target.value)}><option value="product_id">Owned product</option><option value="competitor_product_id">Competitor product</option></select><select value={value} onChange={e=>setValue(e.target.value)}><option value="">Select identity</option>{options.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><input value={geo} onChange={e=>setGeo(e.target.value)} placeholder="Pincode / geo (optional)"/></Filters>}
function Current({rows}:{rows:Observation[]}){if(!rows.length)return <Empty title="No price observations yet" text="Observed prices will appear after normalized S6 ingestion. No fallback prices are generated."/>;return <div className="table-wrap"><table className="data-table"><thead><tr><th>Identity</th><th>Observed price</th><th>MRP</th><th>Effective</th><th>Discount</th><th>Availability</th><th>Sellers</th><th>Geo</th><th>Observed</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><div className="primary-cell"><strong>{x.marketplace_product_id}</strong><span>{x.product_id?"Owned":x.competitor_product_id?"Competitor":"Unmapped"} · {x.primary_seller_name||"Seller unknown"}</span></div></td><td>{formatMoney(x.primary_price,x.currency)}</td><td>{formatMoney(x.list_price,x.currency)}</td><td>{formatMoney(x.effective_price,x.currency)}</td><td>{x.discount_percent!==null?`${x.discount_percent}%`:"Unavailable"}</td><td><span className={`status ${x.availability_status==="available"?"approved":"draft"}`}>{x.availability_status.replaceAll("_"," ")}</span></td><td>{x.seller_count??"Unknown"}</td><td>{x.geo_code||"All"}</td><td>{when(x.observed_at)}</td></tr>)}</tbody></table></div>}
function History({rows}:{rows:HistoryRow[]}){if(!rows.length)return <Empty title="No price history" text="No observations exist for this identity and location."/>;return <div className="table-wrap"><table className="data-table"><thead><tr><th>Observed</th><th>Price</th><th>MRP</th><th>Effective</th><th>Discount</th><th>Sellers</th><th>Availability</th><th>Geo</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{when(x.observed_at)}</td><td>{formatMoney(x.primary_price,x.currency)}</td><td>{formatMoney(x.mrp,x.currency)}</td><td>{formatMoney(x.effective_price,x.currency)}</td><td>{x.discount_percent!==null?`${x.discount_percent}%`:"Unavailable"}</td><td>{x.seller_count??"Unknown"}</td><td>{x.availability_status.replaceAll("_"," ")}</td><td>{x.geo_code||"All"}</td></tr>)}</tbody></table></div>}
function Offers({row}:{row:Observation|undefined}){if(!row)return <Empty title="No observation selected" text="Select an observed product/context to inspect its seller offers."/>;if(!row.offers.length)return <Empty title="No seller offers observed" text="Seller details were not present in this normalized observation."/>;return <div className="table-wrap"><table className="data-table"><thead><tr><th>Seller</th><th>Offer</th><th>Shipping</th><th>Coupon</th><th>Effective</th><th>Fulfillment</th><th>Status</th></tr></thead><tbody>{row.offers.map(x=><tr key={x.id}><td>{x.seller_name}{x.is_featured_offer?<span className="badge badge-fresh"> Featured</span>:null}</td><td>{formatMoney(x.offer_price,row.currency)}</td><td>{formatMoney(x.shipping_amount,row.currency)}</td><td>{x.coupon_text||"Unavailable"}</td><td>{formatMoney(x.effective_price,row.currency)}</td><td>{x.fulfillment_type||"Unknown"}</td><td>{x.availability_status}</td></tr>)}</tbody></table></div>}
function Events({rows}:{rows:Event[]}){if(!rows.length)return <Empty title="No price movements yet" text="The first observation is a quiet baseline. Later movements and availability transitions appear here."/>;return <div className="table-wrap"><table className="data-table"><thead><tr><th>Observed</th><th>Product</th><th>Geo</th><th>Event</th><th>Previous</th><th>New</th><th>Movement</th><th>Percent</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{when(x.observed_at)}</td><td>{x.marketplace_product_id}</td><td>{x.geo_code||"All"}</td><td>{x.event_type.replaceAll("_"," ")}</td><td>{formatMoney(x.previous_price,x.currency)}</td><td>{formatMoney(x.new_price,x.currency)}</td><td>{formatMovement(x.absolute_change,x.currency)}</td><td>{x.percent_change!==null?`${x.percent_change}%`:"Unavailable"}</td></tr>)}</tbody></table></div>}
function Compare({value}:{value:Comparison}){const fields:[keyof typeof value.owned,string][]=[["primary_price","Observed price"],["effective_price","Effective price"],["mrp","MRP"],["discount_percent","Discount %"],["seller_count","Seller count"],["availability_status","Availability"]];return <div className="comparison-wrap"><table className="data-table"><thead><tr><th>Metric</th><th>Owned</th><th>Competitor</th></tr></thead><tbody>{fields.map(([key,label])=><tr key={key}><td>{label}</td><td>{String(value.owned[key]??"Unavailable")}</td><td>{String(value.competitor[key]??"Unavailable")}</td></tr>)}</tbody></table><div className="card"><span>Deterministic signals</span><p>{value.signals.map(x=>x.replaceAll("_"," ")).join(" · ")||"No comparison signal supported by current data"}</p></div></div>}
