"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {comparison,completeness,dashboard,detail,history} from "./api";
import type {Change,Comparison,Completeness,History,List,ProductOption,Snapshot} from "./types";
type Tab="snapshots"|"history"|"changes"|"completeness"|"comparison";
type Data={snapshots:List<Snapshot>;changes:List<Change>;products:ProductOption[];competitors:ProductOption[]};
const tabs:[Tab,string][]=[["snapshots","Snapshots"],["history","History"],["changes","Changes"],["completeness","Completeness"],["comparison","Comparison"]];
export const formatScore=(value:number|null)=>value===null?"—":`${value}/100`;
const when=(v:string)=>new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));
const show=(v:unknown)=>{if(v===null||v===undefined||v==="")return "—";const s=typeof v==="string"?v:JSON.stringify(v);return s.length>90?`${s.slice(0,87)}…`:s};
export default function ListingIntelligenceClient(){
 const [data,setData]=useState<Data>({snapshots:{items:[],total:0,limit:100,offset:0},changes:{items:[],total:0,limit:100,offset:0},products:[],competitors:[]});const [tab,setTab]=useState<Tab>("snapshots");const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [selected,setSelected]=useState<Snapshot|null>(null);const [identityType,setIdentityType]=useState("product_id");const [identity,setIdentity]=useState("");const [owned,setOwned]=useState("");const [competitor,setCompetitor]=useState("");const [historyRows,setHistoryRows]=useState<History[]|null>(null);const [score,setScore]=useState<Completeness|null>(null);const [compare,setCompare]=useState<Comparison|null>(null);
 const refresh=useCallback(async()=>{setLoading(true);setError("");try{const d=await dashboard();setData(d);setOwned(x=>x||d.products[0]?.id||"");setCompetitor(x=>x||d.competitors[0]?.id||"");}catch(e){setError(e instanceof Error?e.message:"Unable to load listing intelligence");}finally{setLoading(false);}},[]);useEffect(()=>{void refresh()},[refresh]);
 const latest=data.snapshots.items[0];const average=useMemo(()=>data.snapshots.items.length?Math.round(data.snapshots.items.reduce((a,x)=>a+x.completeness_score,0)/data.snapshots.items.length):null,[data.snapshots.items]);
 const options=identityType==="product_id"?data.products:data.competitors;function query(){return new URLSearchParams({[identityType]:identity}).toString()}
 async function run(kind:"history"|"score"){if(!identity){setError("Select a listing identity first.");return}setBusy(true);setError("");try{if(kind==="history")setHistoryRows((await history(query())).items);else setScore(await completeness(query()));}catch(e){setError(e instanceof Error?e.message:"Unable to load listing analytics")}finally{setBusy(false)}}
 async function runComparison(){if(!owned||!competitor){setError("Select both products first.");return}setBusy(true);try{setCompare(await comparison(owned,competitor))}catch(e){setError(e instanceof Error?e.message:"Unable to compare listings")}finally{setBusy(false)}}
 return <div className="rank-shell"><div className="rank-summary"><Card label="Total snapshots" value={data.snapshots.total}/><Card label="Latest capture" value={latest?when(latest.captured_at):"—"}/><Card label="Average completeness" value={formatScore(average)}/><Card label="Recent changes" value={data.changes.total}/></div><div className="universe-panel"><div className="universe-toolbar"><div className="tabs">{tabs.map(([k,l])=><button key={k} className={`tab ${tab===k?"active":""}`} onClick={()=>setTab(k)}>{l}</button>)}</div><button className="button" disabled={loading} onClick={()=>void refresh()}>{loading?"Refreshing…":"Refresh"}</button></div>{error&&<div className="error-banner" role="alert">{error}</div>}
 {loading?<Loading/>:<>{tab==="snapshots"&&<Snapshots rows={data.snapshots.items} names={[...data.products,...data.competitors]} open={async id=>{setBusy(true);try{setSelected(await detail(id))}finally{setBusy(false)}}}/>} {(tab==="history"||tab==="completeness")&&<Identity type={identityType} setType={v=>{setIdentityType(v);setIdentity("")}} value={identity} setValue={setIdentity} options={options}/>} {tab==="history"&&<Action label="Load history" busy={busy} run={()=>void run("history")}/>} {tab==="history"&&historyRows&&<HistoryTable rows={historyRows}/>} {tab==="changes"&&<Changes rows={data.changes.items}/>} {tab==="completeness"&&<Action label="Load completeness" busy={busy} run={()=>void run("score")}/>} {tab==="completeness"&&score&&<Score value={score}/>} {tab==="comparison"&&<CompareFilters products={data.products} competitors={data.competitors} owned={owned} competitor={competitor} setOwned={setOwned} setCompetitor={setCompetitor}/>} {tab==="comparison"&&<Action label="Compare latest listings" busy={busy} run={()=>void runComparison()}/>} {tab==="comparison"&&compare&&<Compare value={compare}/>}</>}
 </div>{selected&&<div className="modal-backdrop"><div className="entity-modal listing-detail"><div className="modal-header"><div><div className="eyebrow">Normalized snapshot</div><h2>{selected.title||selected.marketplace_product_id}</h2><span className="muted">{when(selected.captured_at)} · {formatScore(selected.completeness_score)}</span></div><button className="icon-button" onClick={()=>setSelected(null)}>×</button></div><div className="listing-content"><Section label="Brand / category" text={`${selected.brand||"Unknown"} · ${selected.category_path||"Uncategorised"}`}/><Section label="Bullets" text={selected.bullets.length?selected.bullets.map((x,i)=>`${i+1}. ${x}`).join("\n"):"None"}/><Section label="Description" text={selected.description||"None"}/><Section label="A+ content" text={selected.a_plus_present?`${selected.a_plus_sections.length} normalized sections`:"Not present"}/><Section label="Assets" text={`${selected.image_count} images · ${selected.video_count} videos · ${selected.variation_count??0} variations`}/><Section label="Images" text={selected.image_urls.join("\n")||selected.image_hashes.join("\n")||"None"}/><Section label="Lineage" text={`${selected.parser_version||"No parser version"}${selected.source_url?` · ${selected.source_url}`:""}`}/></div></div></div>}</div>}
function Card({label,value}:{label:string;value:string|number}){return <div className="card"><span>{label}</span><strong>{value}</strong></div>}function Loading(){return <div className="loading-state"><span className="spinner"/>Loading live S5 data…</div>}function Empty({title,text}:{title:string;text:string}){return <div className="empty-state"><strong>{title}</strong><span>{text}</span></div>}function Action({label,busy,run}:{label:string;busy:boolean;run:()=>void}){return <div className="rank-action"><button className="button primary" disabled={busy} onClick={run}>{busy?"Loading…":label}</button></div>}
function Identity({type,setType,value,setValue,options}:{type:string;setType:(v:string)=>void;value:string;setValue:(v:string)=>void;options:ProductOption[]}){return <div className="keyword-filters"><select value={type} onChange={e=>setType(e.target.value)}><option value="product_id">Owned product</option><option value="competitor_product_id">Competitor product</option></select><select value={value} onChange={e=>setValue(e.target.value)}><option value="">Select identity</option>{options.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div>}
function Snapshots({rows,names,open}:{rows:Snapshot[];names:ProductOption[];open:(id:string)=>void}){if(!rows.length)return <Empty title="No listing snapshots yet" text="Ingest normalized product-detail content through the S5 API."/>;const name=(x:Snapshot)=>names.find(n=>n.id===(x.product_id||x.competitor_product_id))?.name||x.marketplace_product_id;return <div className="table-wrap"><table className="data-table"><thead><tr><th>Captured</th><th>Identity</th><th>Title</th><th>Images</th><th>Bullets</th><th>A+</th><th>Video</th><th>Complete</th><th/></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{when(x.captured_at)}</td><td><div className="primary-cell"><strong>{name(x)}</strong><span>{x.product_id?"Owned":x.competitor_product_id?"Competitor":"Unmapped"} · {x.marketplace_product_id}</span></div></td><td className="long-cell">{x.title||"—"}</td><td>{x.image_count}</td><td>{x.bullets.length}</td><td>{x.a_plus_present?"Yes":"No"}</td><td>{x.video_present?"Yes":"No"}</td><td>{formatScore(x.completeness_score)}</td><td><button className="text-button" onClick={()=>void open(x.id)}>View</button></td></tr>)}</tbody></table></div>}
function HistoryTable({rows}:{rows:History[]}){if(!rows.length)return <Empty title="No listing history" text="No snapshots exist for this identity."/>;return <div className="table-wrap"><table className="data-table"><thead><tr><th>Captured</th><th>Title</th><th>Bullets</th><th>Images</th><th>A+</th><th>Video</th><th>Variations</th><th>Complete</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{when(x.captured_at)}</td><td className="long-cell">{x.title||"—"}</td><td>{x.bullet_count}</td><td>{x.image_count}</td><td>{x.a_plus_present?"Yes":"No"}</td><td>{x.video_present?"Yes":"No"}</td><td>{x.variation_count??0}</td><td>{formatScore(x.completeness_score)}</td></tr>)}</tbody></table></div>}
function Changes({rows}:{rows:Change[]}){if(!rows.length)return <Empty title="No listing changes yet" text="The first snapshot is a quiet baseline; later field changes appear here."/>;return <div className="table-wrap"><table className="data-table"><thead><tr><th>Observed</th><th>SKU</th><th>Field</th><th>Change</th><th>Previous</th><th>New</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{when(x.observed_at)}</td><td>{x.marketplace_product_id}</td><td>{x.field_name.replaceAll("_"," ")}</td><td><span className={`status ${x.change_type==="added"?"approved":"draft"}`}>{x.change_type}</span></td><td className="long-cell">{show(x.old_value)}</td><td className="long-cell">{show(x.new_value)}</td></tr>)}</tbody></table></div>}
function Score({value}:{value:Completeness}){return <div className="listing-score"><Card label="Completeness" value={formatScore(value.score)}/><div className="card component-list"><strong>Component breakdown</strong>{Object.entries(value.breakdown).map(([k,v])=><div key={k}><span>{k.replaceAll("_"," ")}</span><b>{v} points</b></div>)}</div><div className="card"><span>Achieved</span><p>{value.achieved_components.map(x=>x.replaceAll("_"," ")).join(", ")||"None"}</p><span>Missing</span><p>{value.missing_components.map(x=>x.replaceAll("_"," ")).join(", ")||"None"}</p></div></div>}
function CompareFilters({products,competitors,owned,competitor,setOwned,setCompetitor}:{products:ProductOption[];competitors:ProductOption[];owned:string;competitor:string;setOwned:(v:string)=>void;setCompetitor:(v:string)=>void}){return <div className="keyword-filters"><select value={owned} onChange={e=>setOwned(e.target.value)}><option value="">Owned product</option>{products.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={competitor} onChange={e=>setCompetitor(e.target.value)}><option value="">Competitor product</option>{competitors.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div>}
function Compare({value}:{value:Comparison}){const keys=Object.keys(value.owned) as (keyof typeof value.owned)[];return <div className="comparison-wrap"><table className="data-table"><thead><tr><th>Metric</th><th>Owned</th><th>Competitor</th></tr></thead><tbody>{keys.map(k=><tr key={k}><td>{k.replaceAll("_"," ")}</td><td>{String(value.owned[k])}</td><td>{String(value.competitor[k])}</td></tr>)}</tbody></table><div className="card"><span>Deterministic gaps</span><p>{value.gaps.map(x=>x.replaceAll("_"," ")).join(" · ")||"No measured gaps"}</p></div></div>}
function Section({label,text}:{label:string;text:string}){return <section><strong>{label}</strong><p>{text}</p></section>}
